name: 手动触发刷步数

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      user:
        description: '用户名'
        required: false
        default: '2929188233@qq.com'
      pwd:
        description: '密码'
        required: false
        default: 'Huawei@123'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: 开始
        run: |
          pip3 install requests
          user='${{ github.event.inputs.user }}'
          passwd='${{ github.event.inputs.pwd }}'
          python3 main.py ${user} ${passwd}
